CREATE TABLE IF NOT EXISTS alerts (
  alert_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_key varchar(120) NOT NULL,
  source_type varchar(60) NOT NULL DEFAULT 'system',
  source_ref_id varchar(160) NULL,
  dedupe_key varchar(180) NULL,
  tenant_id uuid NULL REFERENCES tenants(tenant_id) ON DELETE SET NULL,
  severity varchar(20) NOT NULL DEFAULT 'warning',
  status varchar(30) NOT NULL DEFAULT 'PENDIENTE',
  title varchar(180) NOT NULL,
  message text NOT NULL,
  summary_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  context_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  assigned_platform_account_id uuid NULL REFERENCES platform_accounts(platform_account_id) ON DELETE SET NULL,
  first_seen_at timestamptz NOT NULL DEFAULT NOW(),
  last_seen_at timestamptz NOT NULL DEFAULT NOW(),
  occurrences int NOT NULL DEFAULT 1,
  acknowledged_at timestamptz NULL,
  mitigated_at timestamptz NULL,
  resolved_at timestamptz NULL,
  closed_at timestamptz NULL,
  sla_due_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_status_severity_last_seen
  ON alerts (status, severity, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_rule_status
  ON alerts (rule_key, status, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_dedupe_key
  ON alerts (dedupe_key);

CREATE TABLE IF NOT EXISTS alert_events (
  alert_event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_id bigint NOT NULL REFERENCES alerts(alert_id) ON DELETE CASCADE,
  event_type varchar(60) NOT NULL,
  from_status varchar(30) NULL,
  to_status varchar(30) NULL,
  actor_platform_account_id uuid NULL REFERENCES platform_accounts(platform_account_id) ON DELETE SET NULL,
  note_text text NULL,
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alert_events_alert_created
  ON alert_events (alert_id, created_at DESC);

CREATE TABLE IF NOT EXISTS incident_notes (
  incident_note_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_id bigint NOT NULL REFERENCES alerts(alert_id) ON DELETE CASCADE,
  author_platform_account_id uuid NULL REFERENCES platform_accounts(platform_account_id) ON DELETE SET NULL,
  note_type varchar(40) NOT NULL DEFAULT 'investigation',
  body text NOT NULL,
  is_internal boolean NOT NULL DEFAULT TRUE,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_incident_notes_alert_created
  ON incident_notes (alert_id, created_at DESC);

ALTER TABLE platform_alert_deliveries
  DROP CONSTRAINT IF EXISTS platform_alert_deliveries_alert_id_fkey;

INSERT INTO alerts (
  alert_id,
  rule_key,
  source_type,
  source_ref_id,
  tenant_id,
  severity,
  status,
  title,
  message,
  summary_json,
  context_json,
  first_seen_at,
  last_seen_at,
  occurrences,
  resolved_at,
  created_at,
  updated_at
)
SELECT
  pae.alert_id,
  pae.event_key,
  'legacy_platform_alert',
  pae.alert_id::text,
  pae.tenant_id,
  pae.severity,
  CASE
    WHEN pae.status = 'resolved' THEN 'RESUELTO'
    ELSE 'PENDIENTE'
  END,
  pae.title,
  pae.message,
  COALESCE(pae.payload_json, '{}'::jsonb),
  jsonb_build_object('legacy_status', pae.status),
  pae.created_at,
  COALESCE(pae.resolved_at, pae.created_at),
  1,
  pae.resolved_at,
  pae.created_at,
  COALESCE(pae.resolved_at, pae.created_at)
FROM platform_alert_events pae
WHERE NOT EXISTS (
  SELECT 1
  FROM alerts a
  WHERE a.alert_id = pae.alert_id
);

INSERT INTO alert_events (
  alert_id,
  event_type,
  from_status,
  to_status,
  note_text,
  payload_json,
  created_at
)
SELECT
  pae.alert_id,
  CASE
    WHEN pae.status = 'resolved' THEN 'ALERT_MIGRATED_RESOLVED'
    ELSE 'ALERT_MIGRATED_OPEN'
  END,
  NULL,
  CASE
    WHEN pae.status = 'resolved' THEN 'RESUELTO'
    ELSE 'PENDIENTE'
  END,
  pae.resolution_note,
  COALESCE(pae.payload_json, '{}'::jsonb),
  COALESCE(pae.resolved_at, pae.created_at)
FROM platform_alert_events pae
WHERE EXISTS (
  SELECT 1
  FROM alerts a
  WHERE a.alert_id = pae.alert_id
)
AND NOT EXISTS (
  SELECT 1
  FROM alert_events ae
  WHERE ae.alert_id = pae.alert_id
);

ALTER TABLE platform_alert_deliveries
  ADD CONSTRAINT platform_alert_deliveries_alert_id_fkey
  FOREIGN KEY (alert_id) REFERENCES alerts(alert_id) ON DELETE CASCADE;
