const express = require("express");
const router = express.Router();
const c = require("../controllers/auth.controller");
const { requireAuth } = require("../middlewares/auth");
const { validate } = require("../middlewares/validate");
const { loginRateLimit } = require("../middlewares/loginRateLimit");
const s = require("../utils/schemas");
router.post('/login', loginRateLimit, validate(s.login), c.unifiedLogin);
router.post('/login/root', loginRateLimit, validate(s.login), c.login);
router.post('/login/tenant', loginRateLimit, validate(s.tenantLogin), c.tenantLogin);
router.post('/refresh', validate(s.refresh), c.refresh);
router.post('/logout', validate(s.logout), c.logout);
router.post('/tenant/refresh', validate(s.refresh), c.tenantRefresh);
router.post('/tenant/logout', validate(s.logout), c.tenantLogout);
router.post('/tenant/context', requireAuth, validate(s.tenantContext), c.tenantSwitchContext);
router.post('/password-recovery/request', validate(s.recoveryRequest), c.requestRecovery);
router.post('/password-recovery/reset', validate(s.recoveryReset), c.resetPassword);
router.get('/me', requireAuth, c.me);
router.get('/access', requireAuth, c.platformAccess);
router.get('/tenant/me', requireAuth, c.tenantMe);
router.get('/tenant/access', requireAuth, c.tenantAccess);
module.exports = router;
