const express = require("express");
const router = express.Router();
const c = require("../controllers/tenants.controller");
const users = require("../controllers/tenantUsers.controller");
const { requireAuth, requirePermission } = require("../middlewares/auth");
const { validate } = require("../middlewares/validate");
const s = require("../utils/schemas");
router.get('/', requireAuth, requirePermission('tenants.read'), c.list);
router.get('/:tenantId', requireAuth, requirePermission('tenants.read'), c.detail);
router.post('/', requireAuth, requirePermission('tenants.manage'), validate(s.createTenant), c.create);
router.patch('/:tenantId', requireAuth, requirePermission('tenants.manage'), validate(s.updateTenant), c.update);
router.post('/:tenantId/suspend', requireAuth, requirePermission('tenants.manage'), c.suspend);
router.get('/:tenantId/roles', requireAuth, requirePermission('tenant_modules.read'), c.listTenantRoles);
router.put('/:tenantId/roles/:roleCode/access', requireAuth, requirePermission('tenant_modules.manage'), validate(s.setTenantRoleAccess), c.setTenantRoleAccess);
router.get('/:tenantId/roles/:roleCode', requireAuth, requirePermission('tenant_modules.read'), c.getTenantRole);
router.get('/:tenantId/users', requireAuth, requirePermission('tenants.read'), users.list);
router.post('/:tenantId/users', requireAuth, requirePermission('tenants.manage'), validate(s.createTenantUser), users.create);
router.get('/:tenantId/users/:userId', requireAuth, requirePermission('tenants.read'), users.detail);
router.patch('/:tenantId/users/:userId', requireAuth, requirePermission('tenants.manage'), validate(s.updateTenantUser), users.update);
router.put('/:tenantId/users/:userId/roles', requireAuth, requirePermission('tenants.manage'), validate(s.tenantUserRoles), users.setRoles);
router.get('/:tenantId/users/:userId/effective-access', requireAuth, requirePermission('tenant_modules.read'), users.effectiveAccess);
router.get('/:tenantId/modules/effective', requireAuth, requirePermission('tenant_modules.read'), c.listEffectiveModules);
router.get('/:tenantId/modules', requireAuth, requirePermission('tenant_modules.read'), c.listModules);
router.put('/:tenantId/modules', requireAuth, requirePermission('tenant_modules.manage'), validate(s.setTenantModules), c.setModules);
module.exports = router;
